/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MilestoneIntegrationPlatformVmsResTfulApi);
  }
}(this, function(expect, MilestoneIntegrationPlatformVmsResTfulApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AddPatrollingEntryRequestBody', function() {
      beforeEach(function() {
        instance = new MilestoneIntegrationPlatformVmsResTfulApi.AddPatrollingEntryRequestBody();
      });

      it('should create an instance of AddPatrollingEntryRequestBody', function() {
        // TODO: update the code to test AddPatrollingEntryRequestBody
        expect(instance).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.AddPatrollingEntryRequestBody);
      });

      it('should have the property order (base name: "order")', function() {
        // TODO: update the code to test the property order
        expect(instance).to.have.property('order');
        // expect(instance.order).to.be(expectedValueLiteral);
      });

      it('should have the property presetId (base name: "presetId")', function() {
        // TODO: update the code to test the property presetId
        expect(instance).to.have.property('presetId');
        // expect(instance.presetId).to.be(expectedValueLiteral);
      });

      it('should have the property waitTime (base name: "waitTime")', function() {
        // TODO: update the code to test the property waitTime
        expect(instance).to.have.property('waitTime');
        // expect(instance.waitTime).to.be(expectedValueLiteral);
      });

    });
  });

}));
