/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MilestoneIntegrationPlatformVmsResTfulApi);
  }
}(this, function(expect, MilestoneIntegrationPlatformVmsResTfulApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ApplyCamerasAndLayoutRequestBody', function() {
      beforeEach(function() {
        instance = new MilestoneIntegrationPlatformVmsResTfulApi.ApplyCamerasAndLayoutRequestBody();
      });

      it('should create an instance of ApplyCamerasAndLayoutRequestBody', function() {
        // TODO: update the code to test ApplyCamerasAndLayoutRequestBody
        expect(instance).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.ApplyCamerasAndLayoutRequestBody);
      });

      it('should have the property cameraPaths (base name: "cameraPaths")', function() {
        // TODO: update the code to test the property cameraPaths
        expect(instance).to.have.property('cameraPaths');
        // expect(instance.cameraPaths).to.be(expectedValueLiteral);
      });

      it('should have the property cameraGroupPaths (base name: "cameraGroupPaths")', function() {
        // TODO: update the code to test the property cameraGroupPaths
        expect(instance).to.have.property('cameraGroupPaths');
        // expect(instance.cameraGroupPaths).to.be(expectedValueLiteral);
      });

      it('should have the property beginPosition (base name: "beginPosition")', function() {
        // TODO: update the code to test the property beginPosition
        expect(instance).to.have.property('beginPosition');
        // expect(instance.beginPosition).to.be(expectedValueLiteral);
      });

      it('should have the property layoutPath (base name: "layoutPath")', function() {
        // TODO: update the code to test the property layoutPath
        expect(instance).to.have.property('layoutPath');
        // expect(instance.layoutPath).to.be(expectedValueLiteral);
      });

    });
  });

}));
