/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MilestoneIntegrationPlatformVmsResTfulApi);
  }
}(this, function(expect, MilestoneIntegrationPlatformVmsResTfulApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ChangePasswordHardwareRequestBody', function() {
      beforeEach(function() {
        instance = new MilestoneIntegrationPlatformVmsResTfulApi.ChangePasswordHardwareRequestBody();
      });

      it('should create an instance of ChangePasswordHardwareRequestBody', function() {
        // TODO: update the code to test ChangePasswordHardwareRequestBody
        expect(instance).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.ChangePasswordHardwareRequestBody);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property updatePasswordOnDevice (base name: "updatePasswordOnDevice")', function() {
        // TODO: update the code to test the property updatePasswordOnDevice
        expect(instance).to.have.property('updatePasswordOnDevice');
        // expect(instance.updatePasswordOnDevice).to.be(expectedValueLiteral);
      });

    });
  });

}));
