/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MilestoneIntegrationPlatformVmsResTfulApi);
  }
}(this, function(expect, MilestoneIntegrationPlatformVmsResTfulApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('HardwareScanRequestBody', function() {
      beforeEach(function() {
        instance = new MilestoneIntegrationPlatformVmsResTfulApi.HardwareScanRequestBody();
      });

      it('should create an instance of HardwareScanRequestBody', function() {
        // TODO: update the code to test HardwareScanRequestBody
        expect(instance).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.HardwareScanRequestBody);
      });

      it('should have the property hardwareAddress (base name: "hardwareAddress")', function() {
        // TODO: update the code to test the property hardwareAddress
        expect(instance).to.have.property('hardwareAddress');
        // expect(instance.hardwareAddress).to.be(expectedValueLiteral);
      });

      it('should have the property hardwareDriverIds (base name: "hardwareDriverIds")', function() {
        // TODO: update the code to test the property hardwareDriverIds
        expect(instance).to.have.property('hardwareDriverIds');
        // expect(instance.hardwareDriverIds).to.be(expectedValueLiteral);
      });

      it('should have the property userName (base name: "userName")', function() {
        // TODO: update the code to test the property userName
        expect(instance).to.have.property('userName');
        // expect(instance.userName).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

      it('should have the property useDefaultCredentials (base name: "useDefaultCredentials")', function() {
        // TODO: update the code to test the property useDefaultCredentials
        expect(instance).to.have.property('useDefaultCredentials');
        // expect(instance.useDefaultCredentials).to.be(expectedValueLiteral);
      });

    });
  });

}));
