/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MilestoneIntegrationPlatformVmsResTfulApi);
  }
}(this, function(expect, MilestoneIntegrationPlatformVmsResTfulApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MipKinds', function() {
      beforeEach(function() {
        instance = new MilestoneIntegrationPlatformVmsResTfulApi.MipKinds();
      });

      it('should create an instance of MipKinds', function() {
        // TODO: update the code to test MipKinds
        expect(instance).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.MipKinds);
      });

      it('should have the property displayName (base name: "displayName")', function() {
        // TODO: update the code to test the property displayName
        expect(instance).to.have.property('displayName');
        // expect(instance.displayName).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property pluginId (base name: "pluginId")', function() {
        // TODO: update the code to test the property pluginId
        expect(instance).to.have.property('pluginId');
        // expect(instance.pluginId).to.be(expectedValueLiteral);
      });

      it('should have the property pluginName (base name: "pluginName")', function() {
        // TODO: update the code to test the property pluginName
        expect(instance).to.have.property('pluginName');
        // expect(instance.pluginName).to.be(expectedValueLiteral);
      });

      it('should have the property kindType (base name: "kindType")', function() {
        // TODO: update the code to test the property kindType
        expect(instance).to.have.property('kindType');
        // expect(instance.kindType).to.be(expectedValueLiteral);
      });

      it('should have the property securityAction (base name: "securityAction")', function() {
        // TODO: update the code to test the property securityAction
        expect(instance).to.have.property('securityAction');
        // expect(instance.securityAction).to.be(expectedValueLiteral);
      });

      it('should have the property displayOnGisMap (base name: "displayOnGisMap")', function() {
        // TODO: update the code to test the property displayOnGisMap
        expect(instance).to.have.property('displayOnGisMap');
        // expect(instance.displayOnGisMap).to.be(expectedValueLiteral);
      });

      it('should have the property parentKind (base name: "parentKind")', function() {
        // TODO: update the code to test the property parentKind
        expect(instance).to.have.property('parentKind');
        // expect(instance.parentKind).to.be(expectedValueLiteral);
      });

      it('should have the property dataVersion (base name: "dataVersion")', function() {
        // TODO: update the code to test the property dataVersion
        expect(instance).to.have.property('dataVersion');
        // expect(instance.dataVersion).to.be(expectedValueLiteral);
      });

      it('should have the property modifiedUser (base name: "modifiedUser")', function() {
        // TODO: update the code to test the property modifiedUser
        expect(instance).to.have.property('modifiedUser');
        // expect(instance.modifiedUser).to.be(expectedValueLiteral);
      });

      it('should have the property lastModified (base name: "lastModified")', function() {
        // TODO: update the code to test the property lastModified
        expect(instance).to.have.property('lastModified');
        // expect(instance.lastModified).to.be(expectedValueLiteral);
      });

      it('should have the property relations (base name: "relations")', function() {
        // TODO: update the code to test the property relations
        expect(instance).to.have.property('relations');
        // expect(instance.relations).to.be(expectedValueLiteral);
      });

    });
  });

}));
