/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MilestoneIntegrationPlatformVmsResTfulApi);
  }
}(this, function(expect, MilestoneIntegrationPlatformVmsResTfulApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PtzSessionTimeouts', function() {
      beforeEach(function() {
        instance = new MilestoneIntegrationPlatformVmsResTfulApi.PtzSessionTimeouts();
      });

      it('should create an instance of PtzSessionTimeouts', function() {
        // TODO: update the code to test PtzSessionTimeouts
        expect(instance).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.PtzSessionTimeouts);
      });

      it('should have the property displayName (base name: "displayName")', function() {
        // TODO: update the code to test the property displayName
        expect(instance).to.have.property('displayName');
        // expect(instance.displayName).to.be(expectedValueLiteral);
      });

      it('should have the property manualPTZTimeout (base name: "manualPTZTimeout")', function() {
        // TODO: update the code to test the property manualPTZTimeout
        expect(instance).to.have.property('manualPTZTimeout');
        // expect(instance.manualPTZTimeout).to.be(expectedValueLiteral);
      });

      it('should have the property pausePatrollingTimeout (base name: "pausePatrollingTimeout")', function() {
        // TODO: update the code to test the property pausePatrollingTimeout
        expect(instance).to.have.property('pausePatrollingTimeout');
        // expect(instance.pausePatrollingTimeout).to.be(expectedValueLiteral);
      });

      it('should have the property reservedPTZTimeout (base name: "reservedPTZTimeout")', function() {
        // TODO: update the code to test the property reservedPTZTimeout
        expect(instance).to.have.property('reservedPTZTimeout');
        // expect(instance.reservedPTZTimeout).to.be(expectedValueLiteral);
      });

    });
  });

}));
