/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MilestoneIntegrationPlatformVmsResTfulApi);
  }
}(this, function(expect, MilestoneIntegrationPlatformVmsResTfulApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Stream', function() {
      beforeEach(function() {
        instance = new MilestoneIntegrationPlatformVmsResTfulApi.Stream();
      });

      it('should create an instance of Stream', function() {
        // TODO: update the code to test Stream
        expect(instance).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.Stream);
      });

      it('should have the property displayName (base name: "displayName")', function() {
        // TODO: update the code to test the property displayName
        expect(instance).to.have.property('displayName');
        // expect(instance.displayName).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property streamReferenceId (base name: "streamReferenceId")', function() {
        // TODO: update the code to test the property streamReferenceId
        expect(instance).to.have.property('streamReferenceId');
        // expect(instance.streamReferenceId).to.be(expectedValueLiteral);
      });

      it('should have the property liveDefault (base name: "liveDefault")', function() {
        // TODO: update the code to test the property liveDefault
        expect(instance).to.have.property('liveDefault');
        // expect(instance.liveDefault).to.be(expectedValueLiteral);
      });

      it('should have the property liveMode (base name: "liveMode")', function() {
        // TODO: update the code to test the property liveMode
        expect(instance).to.have.property('liveMode');
        // expect(instance.liveMode).to.be(expectedValueLiteral);
      });

      it('should have the property record (base name: "record")', function() {
        // TODO: update the code to test the property record
        expect(instance).to.have.property('record');
        // expect(instance.record).to.be(expectedValueLiteral);
      });

    });
  });

}));
