/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MilestoneIntegrationPlatformVmsResTfulApi);
  }
}(this, function(expect, MilestoneIntegrationPlatformVmsResTfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MilestoneIntegrationPlatformVmsResTfulApi.CoreApi();
  });

  describe('(package)', function() {
    describe('CoreApi', function() {
      describe('deleteloginProvidersById', function() {
        it('should call deleteloginProvidersById successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteloginProvidersById call and complete the assertions
          /*

          instance.deleteloginProvidersById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20114);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteloginProvidersByIdregisteredClaims', function() {
        it('should call deleteloginProvidersByIdregisteredClaims successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteloginProvidersByIdregisteredClaims call and complete the assertions
          /*

          instance.deleteloginProvidersByIdregisteredClaims(idParent, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20115);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllTranslations', function() {
        it('should call getAllTranslations successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllTranslations call and complete the assertions
          /*

          instance.getAllTranslations(language, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200186);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllaccessControlSystemsInAsites', function() {
        it('should call getAllaccessControlSystemsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllaccessControlSystemsInAsites call and complete the assertions
          /*

          instance.getAllaccessControlSystemsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllalarmDefinitionsInAsites', function() {
        it('should call getAllalarmDefinitionsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllalarmDefinitionsInAsites call and complete the assertions
          /*

          instance.getAllalarmDefinitionsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse2007);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllanalyticsEventsInAsites', function() {
        it('should call getAllanalyticsEventsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllanalyticsEventsInAsites call and complete the assertions
          /*

          instance.getAllanalyticsEventsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse2009);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllbasicUsersInAsites', function() {
        it('should call getAllbasicUsersInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllbasicUsersInAsites call and complete the assertions
          /*

          instance.getAllbasicUsersInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20022);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllcameraGroupsInAsites', function() {
        it('should call getAllcameraGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllcameraGroupsInAsites call and complete the assertions
          /*

          instance.getAllcameraGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20040);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllchildSites', function() {
        it('should call getAllchildSites successfully', function(done) {
          // TODO: uncomment getAllchildSites call and complete the assertions
          /*

          instance.getAllchildSites(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200146);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllchildSitesInAchildSites', function() {
        it('should call getAllchildSitesInAchildSites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllchildSitesInAchildSites call and complete the assertions
          /*

          instance.getAllchildSitesInAchildSites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200146);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllchildSitesInAsites', function() {
        it('should call getAllchildSitesInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllchildSitesInAsites call and complete the assertions
          /*

          instance.getAllchildSitesInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200146);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllclientProfilesInAsites', function() {
        it('should call getAllclientProfilesInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllclientProfilesInAsites call and complete the assertions
          /*

          instance.getAllclientProfilesInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20042);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlleventTypeGroupsInAsites', function() {
        it('should call getAlleventTypeGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlleventTypeGroupsInAsites call and complete the assertions
          /*

          instance.getAlleventTypeGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20046);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllfailoverGroupsInAsites', function() {
        it('should call getAllfailoverGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllfailoverGroupsInAsites call and complete the assertions
          /*

          instance.getAllfailoverGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20052);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllgenericEventDataSourcesInAsites', function() {
        it('should call getAllgenericEventDataSourcesInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllgenericEventDataSourcesInAsites call and complete the assertions
          /*

          instance.getAllgenericEventDataSourcesInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20059);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllgenericEventsInAsites', function() {
        it('should call getAllgenericEventsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllgenericEventsInAsites call and complete the assertions
          /*

          instance.getAllgenericEventsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20050);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllgisMapLocationsInAsites', function() {
        it('should call getAllgisMapLocationsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllgisMapLocationsInAsites call and complete the assertions
          /*

          instance.getAllgisMapLocationsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20061);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllinputEventGroupsInAsites', function() {
        it('should call getAllinputEventGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllinputEventGroupsInAsites call and complete the assertions
          /*

          instance.getAllinputEventGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20081);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlllayoutGroupsInAsites', function() {
        it('should call getAlllayoutGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlllayoutGroupsInAsites call and complete the assertions
          /*

          instance.getAlllayoutGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20083);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlllicenseDetailsInAlicenseInformations', function() {
        it('should call getAlllicenseDetailsInAlicenseInformations successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlllicenseDetailsInAlicenseInformations call and complete the assertions
          /*

          instance.getAlllicenseDetailsInAlicenseInformations(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20091);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlllicenseInformations', function() {
        it('should call getAlllicenseInformations successfully', function(done) {
          // TODO: uncomment getAlllicenseInformations call and complete the assertions
          /*

          instance.getAlllicenseInformations(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20087);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlllicenseInformationsInAsites', function() {
        it('should call getAlllicenseInformationsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlllicenseInformationsInAsites call and complete the assertions
          /*

          instance.getAlllicenseInformationsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20087);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlllicenseInstalledProductsInAlicenseInformations', function() {
        it('should call getAlllicenseInstalledProductsInAlicenseInformations successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlllicenseInstalledProductsInAlicenseInformations call and complete the assertions
          /*

          instance.getAlllicenseInstalledProductsInAlicenseInformations(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20092);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlllicenseOverviewAllInAlicenseInformations', function() {
        it('should call getAlllicenseOverviewAllInAlicenseInformations successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlllicenseOverviewAllInAlicenseInformations call and complete the assertions
          /*

          instance.getAlllicenseOverviewAllInAlicenseInformations(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20093);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllloginProviders', function() {
        it('should call getAllloginProviders successfully', function(done) {
          // TODO: uncomment getAllloginProviders call and complete the assertions
          /*

          instance.getAllloginProviders(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20094);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllloginProvidersInAsites', function() {
        it('should call getAllloginProvidersInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllloginProvidersInAsites call and complete the assertions
          /*

          instance.getAllloginProvidersInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20094);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlllprMatchListsInAsites', function() {
        it('should call getAlllprMatchListsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlllprMatchListsInAsites call and complete the assertions
          /*

          instance.getAlllprMatchListsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20097);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllmetadataGroupsInAsites', function() {
        it('should call getAllmetadataGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllmetadataGroupsInAsites call and complete the assertions
          /*

          instance.getAllmetadataGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200102);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllmicrophoneGroupsInAsites', function() {
        it('should call getAllmicrophoneGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllmicrophoneGroupsInAsites call and complete the assertions
          /*

          instance.getAllmicrophoneGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200106);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlloutputGroupsInAsites', function() {
        it('should call getAlloutputGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlloutputGroupsInAsites call and complete the assertions
          /*

          instance.getAlloutputGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200118);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllowner', function() {
        it('should call getAllowner successfully', function(done) {
          // TODO: uncomment getAllowner call and complete the assertions
          /*

          instance.getAllowner(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20018);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllownerInAsites', function() {
        it('should call getAllownerInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllownerInAsites call and complete the assertions
          /*

          instance.getAllownerInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20018);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllpatrollingProfiles', function() {
        it('should call getAllpatrollingProfiles successfully', function(done) {
          // TODO: uncomment getAllpatrollingProfiles call and complete the assertions
          /*

          instance.getAllpatrollingProfiles(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20035);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllrecordingServersInAsites', function() {
        it('should call getAllrecordingServersInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllrecordingServersInAsites call and complete the assertions
          /*

          instance.getAllrecordingServersInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200122);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllregisteredClaims', function() {
        it('should call getAllregisteredClaims successfully', function(done) {
          // TODO: uncomment getAllregisteredClaims call and complete the assertions
          /*

          instance.getAllregisteredClaims(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20096);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllregisteredClaimsInAloginProviders', function() {
        it('should call getAllregisteredClaimsInAloginProviders successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllregisteredClaimsInAloginProviders call and complete the assertions
          /*

          instance.getAllregisteredClaimsInAloginProviders(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20096);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllrolesInAsites', function() {
        it('should call getAllrolesInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllrolesInAsites call and complete the assertions
          /*

          instance.getAllrolesInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200135);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllrulesInAsites', function() {
        it('should call getAllrulesInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllrulesInAsites call and complete the assertions
          /*

          instance.getAllrulesInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200141);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllsaveSearchesInAsites', function() {
        it('should call getAllsaveSearchesInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllsaveSearchesInAsites call and complete the assertions
          /*

          instance.getAllsaveSearchesInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200143);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllsiteAddressesInAchildSites', function() {
        it('should call getAllsiteAddressesInAchildSites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllsiteAddressesInAchildSites call and complete the assertions
          /*

          instance.getAllsiteAddressesInAchildSites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200149);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllsites', function() {
        it('should call getAllsites successfully', function(done) {
          // TODO: uncomment getAllsites call and complete the assertions
          /*

          instance.getAllsites(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200162);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllspeakerGroupsInAsites', function() {
        it('should call getAllspeakerGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllspeakerGroupsInAsites call and complete the assertions
          /*

          instance.getAllspeakerGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200152);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllsystemAddressesInAsites', function() {
        it('should call getAllsystemAddressesInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllsystemAddressesInAsites call and complete the assertions
          /*

          instance.getAllsystemAddressesInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200166);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlltasks', function() {
        it('should call getAlltasks successfully', function(done) {
          // TODO: uncomment getAlltasks call and complete the assertions
          /*

          instance.getAlltasks(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200184);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlltimeProfilesInAsites', function() {
        it('should call getAlltimeProfilesInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlltimeProfilesInAsites call and complete the assertions
          /*

          instance.getAlltimeProfilesInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200167);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlltoolOptions', function() {
        it('should call getAlltoolOptions successfully', function(done) {
          // TODO: uncomment getAlltoolOptions call and complete the assertions
          /*

          instance.getAlltoolOptions(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200168);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlltoolOptionsInAsites', function() {
        it('should call getAlltoolOptionsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlltoolOptionsInAsites call and complete the assertions
          /*

          instance.getAlltoolOptionsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200168);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlluserDefinedEventsInAsites', function() {
        it('should call getAlluserDefinedEventsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAlluserDefinedEventsInAsites call and complete the assertions
          /*

          instance.getAlluserDefinedEventsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20051);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllvideoWallsInAsites', function() {
        it('should call getAllvideoWallsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllvideoWallsInAsites call and complete the assertions
          /*

          instance.getAllvideoWallsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200169);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllviewGroupsInAsites', function() {
        it('should call getAllviewGroupsInAsites successfully', function(done) {
          // TODO: uncomment, update parameter values for getAllviewGroupsInAsites call and complete the assertions
          /*

          instance.getAllviewGroupsInAsites(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200170);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getchildSitesById', function() {
        it('should call getchildSitesById successfully', function(done) {
          // TODO: uncomment, update parameter values for getchildSitesById call and complete the assertions
          /*
          var opts = {};

          instance.getchildSitesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200147);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getlicenseInformationsById', function() {
        it('should call getlicenseInformationsById successfully', function(done) {
          // TODO: uncomment, update parameter values for getlicenseInformationsById call and complete the assertions
          /*
          var opts = {};

          instance.getlicenseInformationsById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20088);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getloginProvidersById', function() {
        it('should call getloginProvidersById successfully', function(done) {
          // TODO: uncomment, update parameter values for getloginProvidersById call and complete the assertions
          /*
          var opts = {};

          instance.getloginProvidersById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20095);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getownerById', function() {
        it('should call getownerById successfully', function(done) {
          // TODO: uncomment, update parameter values for getownerById call and complete the assertions
          /*
          var opts = {};

          instance.getownerById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20019);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getpatrollingProfilesById', function() {
        it('should call getpatrollingProfilesById successfully', function(done) {
          // TODO: uncomment, update parameter values for getpatrollingProfilesById call and complete the assertions
          /*
          var opts = {};

          instance.getpatrollingProfilesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200120);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getregisteredClaimsById', function() {
        it('should call getregisteredClaimsById successfully', function(done) {
          // TODO: uncomment, update parameter values for getregisteredClaimsById call and complete the assertions
          /*
          var opts = {};

          instance.getregisteredClaimsById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200134);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getsitesById', function() {
        it('should call getsitesById successfully', function(done) {
          // TODO: uncomment, update parameter values for getsitesById call and complete the assertions
          /*
          var opts = {};

          instance.getsitesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200164);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('gettasksById', function() {
        it('should call gettasksById successfully', function(done) {
          // TODO: uncomment, update parameter values for gettasksById call and complete the assertions
          /*
          var opts = {};

          instance.gettasksById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200185);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('gettoolOptionsById', function() {
        it('should call gettoolOptionsById successfully', function(done) {
          // TODO: uncomment, update parameter values for gettoolOptionsById call and complete the assertions
          /*
          var opts = {};

          instance.gettoolOptionsById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200172);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchchildSitesById', function() {
        it('should call patchchildSitesById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchchildSitesById call and complete the assertions
          /*
          var opts = {};

          instance.patchchildSitesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200148);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchlicenseInformationsById', function() {
        it('should call patchlicenseInformationsById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchlicenseInformationsById call and complete the assertions
          /*
          var opts = {};

          instance.patchlicenseInformationsById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20089);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchloginProvidersById', function() {
        it('should call patchloginProvidersById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchloginProvidersById call and complete the assertions
          /*
          var opts = {};

          instance.patchloginProvidersById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20114);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchownerById', function() {
        it('should call patchownerById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchownerById call and complete the assertions
          /*
          var opts = {};

          instance.patchownerById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20020);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchpatrollingProfilesById', function() {
        it('should call patchpatrollingProfilesById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchpatrollingProfilesById call and complete the assertions
          /*
          var opts = {};

          instance.patchpatrollingProfilesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse2014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchregisteredClaimsById', function() {
        it('should call patchregisteredClaimsById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchregisteredClaimsById call and complete the assertions
          /*
          var opts = {};

          instance.patchregisteredClaimsById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20115);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchsitesById', function() {
        it('should call patchsitesById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchsitesById call and complete the assertions
          /*
          var opts = {};

          instance.patchsitesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200165);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchtoolOptionsById', function() {
        it('should call patchtoolOptionsById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchtoolOptionsById call and complete the assertions
          /*
          var opts = {};

          instance.patchtoolOptionsById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200173);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postTaskForlicenseInformations', function() {
        it('should call postTaskForlicenseInformations successfully', function(done) {
          // TODO: uncomment, update parameter values for postTaskForlicenseInformations call and complete the assertions
          /*
          var opts = {};

          instance.postTaskForlicenseInformations(id, task, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20090);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postTaskForowner', function() {
        it('should call postTaskForowner successfully', function(done) {
          // TODO: uncomment, update parameter values for postTaskForowner call and complete the assertions
          /*
          var opts = {};

          instance.postTaskForowner(id, task, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20021);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postTaskForpatrollingProfiles', function() {
        it('should call postTaskForpatrollingProfiles successfully', function(done) {
          // TODO: uncomment, update parameter values for postTaskForpatrollingProfiles call and complete the assertions
          /*
          var opts = {};

          instance.postTaskForpatrollingProfiles(id, task, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200121);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postTaskForsites', function() {
        it('should call postTaskForsites successfully', function(done) {
          // TODO: uncomment, update parameter values for postTaskForsites call and complete the assertions
          /*
          var opts = {};

          instance.postTaskForsites(task, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200163);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postloginProvidersById', function() {
        it('should call postloginProvidersById successfully', function(done) {
          // TODO: uncomment, update parameter values for postloginProvidersById call and complete the assertions
          /*
          var opts = {};

          instance.postloginProvidersById(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20114);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postloginProvidersByIdregisteredClaims', function() {
        it('should call postloginProvidersByIdregisteredClaims successfully', function(done) {
          // TODO: uncomment, update parameter values for postloginProvidersByIdregisteredClaims call and complete the assertions
          /*
          var opts = {};

          instance.postloginProvidersByIdregisteredClaims(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20115);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putchildSitesById', function() {
        it('should call putchildSitesById successfully', function(done) {
          // TODO: uncomment, update parameter values for putchildSitesById call and complete the assertions
          /*
          var opts = {};

          instance.putchildSitesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200148);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putlicenseInformationsById', function() {
        it('should call putlicenseInformationsById successfully', function(done) {
          // TODO: uncomment, update parameter values for putlicenseInformationsById call and complete the assertions
          /*
          var opts = {};

          instance.putlicenseInformationsById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20089);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putloginProvidersById', function() {
        it('should call putloginProvidersById successfully', function(done) {
          // TODO: uncomment, update parameter values for putloginProvidersById call and complete the assertions
          /*
          var opts = {};

          instance.putloginProvidersById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20114);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putownerById', function() {
        it('should call putownerById successfully', function(done) {
          // TODO: uncomment, update parameter values for putownerById call and complete the assertions
          /*
          var opts = {};

          instance.putownerById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20020);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putpatrollingProfilesById', function() {
        it('should call putpatrollingProfilesById successfully', function(done) {
          // TODO: uncomment, update parameter values for putpatrollingProfilesById call and complete the assertions
          /*
          var opts = {};

          instance.putpatrollingProfilesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse2014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putregisteredClaimsById', function() {
        it('should call putregisteredClaimsById successfully', function(done) {
          // TODO: uncomment, update parameter values for putregisteredClaimsById call and complete the assertions
          /*
          var opts = {};

          instance.putregisteredClaimsById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20115);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putsitesById', function() {
        it('should call putsitesById successfully', function(done) {
          // TODO: uncomment, update parameter values for putsitesById call and complete the assertions
          /*
          var opts = {};

          instance.putsitesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200165);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('puttoolOptionsById', function() {
        it('should call puttoolOptionsById successfully', function(done) {
          // TODO: uncomment, update parameter values for puttoolOptionsById call and complete the assertions
          /*
          var opts = {};

          instance.puttoolOptionsById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200173);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
