/*
 * Milestone Integration Platform VMS RESTful API
 * VMS Configuration and control for XProtect
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MilestoneIntegrationPlatformVmsResTfulApi);
  }
}(this, function(expect, MilestoneIntegrationPlatformVmsResTfulApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MilestoneIntegrationPlatformVmsResTfulApi.RuleApi();
  });

  describe('(package)', function() {
    describe('RuleApi', function() {
      describe('deleteaudioMessagesById', function() {
        it('should call deleteaudioMessagesById successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteaudioMessagesById call and complete the assertions
          /*

          instance.deleteaudioMessagesById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse2012);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleterulesById', function() {
        it('should call deleterulesById successfully', function(done) {
          // TODO: uncomment, update parameter values for deleterulesById call and complete the assertions
          /*

          instance.deleterulesById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20123);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deletetimeProfilesById', function() {
        it('should call deletetimeProfilesById successfully', function(done) {
          // TODO: uncomment, update parameter values for deletetimeProfilesById call and complete the assertions
          /*

          instance.deletetimeProfilesById(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20127);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllaudioMessages', function() {
        it('should call getAllaudioMessages successfully', function(done) {
          // TODO: uncomment getAllaudioMessages call and complete the assertions
          /*

          instance.getAllaudioMessages(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20015);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllrules', function() {
        it('should call getAllrules successfully', function(done) {
          // TODO: uncomment getAllrules call and complete the assertions
          /*

          instance.getAllrules(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200141);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAlltimeProfiles', function() {
        it('should call getAlltimeProfiles successfully', function(done) {
          // TODO: uncomment getAlltimeProfiles call and complete the assertions
          /*

          instance.getAlltimeProfiles(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200167);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getaudioMessagesById', function() {
        it('should call getaudioMessagesById successfully', function(done) {
          // TODO: uncomment, update parameter values for getaudioMessagesById call and complete the assertions
          /*
          var opts = {};

          instance.getaudioMessagesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20016);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getrulesById', function() {
        it('should call getrulesById successfully', function(done) {
          // TODO: uncomment, update parameter values for getrulesById call and complete the assertions
          /*
          var opts = {};

          instance.getrulesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200142);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('gettimeProfilesById', function() {
        it('should call gettimeProfilesById successfully', function(done) {
          // TODO: uncomment, update parameter values for gettimeProfilesById call and complete the assertions
          /*
          var opts = {};

          instance.gettimeProfilesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse200171);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchaudioMessagesById', function() {
        it('should call patchaudioMessagesById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchaudioMessagesById call and complete the assertions
          /*
          var opts = {};

          instance.patchaudioMessagesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse2012);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchrulesById', function() {
        it('should call patchrulesById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchrulesById call and complete the assertions
          /*
          var opts = {};

          instance.patchrulesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20123);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchtimeProfilesById', function() {
        it('should call patchtimeProfilesById successfully', function(done) {
          // TODO: uncomment, update parameter values for patchtimeProfilesById call and complete the assertions
          /*
          var opts = {};

          instance.patchtimeProfilesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20127);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postTaskForaudioMessages', function() {
        it('should call postTaskForaudioMessages successfully', function(done) {
          // TODO: uncomment, update parameter values for postTaskForaudioMessages call and complete the assertions
          /*

          instance.postTaskForaudioMessages(id, task, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20017);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postaudioMessagesById', function() {
        it('should call postaudioMessagesById successfully', function(done) {
          // TODO: uncomment, update parameter values for postaudioMessagesById call and complete the assertions
          /*
          var opts = {};

          instance.postaudioMessagesById(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse2012);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postrulesById', function() {
        it('should call postrulesById successfully', function(done) {
          // TODO: uncomment, update parameter values for postrulesById call and complete the assertions
          /*
          var opts = {};

          instance.postrulesById(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20123);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('posttimeProfilesById', function() {
        it('should call posttimeProfilesById successfully', function(done) {
          // TODO: uncomment, update parameter values for posttimeProfilesById call and complete the assertions
          /*
          var opts = {};

          instance.posttimeProfilesById(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20127);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putaudioMessagesById', function() {
        it('should call putaudioMessagesById successfully', function(done) {
          // TODO: uncomment, update parameter values for putaudioMessagesById call and complete the assertions
          /*
          var opts = {};

          instance.putaudioMessagesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse2012);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putrulesById', function() {
        it('should call putrulesById successfully', function(done) {
          // TODO: uncomment, update parameter values for putrulesById call and complete the assertions
          /*
          var opts = {};

          instance.putrulesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20123);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('puttimeProfilesById', function() {
        it('should call puttimeProfilesById successfully', function(done) {
          // TODO: uncomment, update parameter values for puttimeProfilesById call and complete the assertions
          /*
          var opts = {};

          instance.puttimeProfilesById(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MilestoneIntegrationPlatformVmsResTfulApi.InlineResponse20127);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
